name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3.5.2

            - name: Copy repository contents via scp
              uses: appleboy/scp-action@v0.1.4
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY }}
              with:
                  source: "."
                  target: "/home/${{ secrets.USERNAME }}/code/cloud/cloud-front"

            - name: Executing remote command
              uses: appleboy/ssh-action@v0.1.8
              with:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY }}
                  script: >
                      cd /home/${{ secrets.USERNAME }}/code/cloud/cloud-front &&
                      cp prod.env .env &&

                      docker container rm -f $(docker ps -a -q --no-trunc --filter name=^/cloud-front-build-container$) > /dev/null 2>&1 ||

                      docker run --rm -v cloud-front-build:/data busybox sh -c "rm -rf /data/*" &&

                      docker build --build-arg REACT_APP_URL=${{ secrets.CORS_URL }} -t cloud-front-build-img -f build.Dockerfile . &&

                      docker run --detach --rm --name cloud-front-build-container -v "cloud-front-build:/home/node/proj/build" cloud-front-build-img
